version: '3'
services:
  influxdb:
    container_name: 'influxdb'
    image: influxdb:latest
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./:/var/lib/ influxdb
    ports:
      - "8086:8086" # influxdb port
      - "8087:8082"
      - "8083:8083" # admin interface port
      - "2003:2003" # graphite port
    entrypoint: ['/bin/bash', '-c']
    networks:
      - influxdb
    command: ['influxd', '-config', '/etc/influxdb/influxdb.conf']
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER='influxadmin'
      - INFLUXDB_ADMIN_PASSWORD='admin'
      - INFLUXDB_DB=db0
      - INFLUXDB_USER='telegraf'
      - INFLUXDB_USER_PASSWORD='telegraf'
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_META_DIR=/var/lib/influxdb
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=true
  telegraf:
    container_name: 'telegraf'
    image: telegraf:latest
    ports:
      - "8125:8125" # StatsD port
      - "8092:8092" # UDP port
      - "8094:8094" # TCP port
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - ./:/var/lib/ influxdb
  aerospike:
    container_name: 'aerospike'
    image: aerospike
    ports:
      - "3000-3003:3000-3003"
  nginx:
    container_name: 'nginx'
    image: nginx
    ports:
      - "8090:8090"
      - "8080:80"
    volumes:
      - ./nginx_status.conf:/etc/nginx/conf.d/nginx_status.conf:ro
  kapacitor:
    container_name: 'kapacitor'
    image: kapacitor:latest
    ports:
      - "9092:9092"
    volumes:
     - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf kapacitor
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_LOGGING_LEVEL=INFO
      - KAPACITOR_REPORTING_ENABLED=false
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  chronograf:
    container_name: 'chronograf'
    image: chronograf:latest
    ports:
      - "8888:8888"
    volumes:
      - ./chronograf:/var/lib/chronograf chronograf
networks: {
  influxdb
}
